[package]
name = "desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.3"
ironboy_core = {path = "../../crates/ironboy_core"}
sdl2 = { version = "0.38.0", features = ["image"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }

